In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
# define the vocabulary size
vocab_size = 10000

In [4]:
# one hot representation
one_hot_repr = [one_hot(words,vocab_size)for words in sent]
print(one_hot_repr)


[[6038, 2979, 8964, 8556], [6038, 2979, 8964, 396], [6038, 7207, 8964, 6711], [7852, 1945, 6301, 2716, 3246], [7852, 1945, 6301, 2716, 4448], [841, 6038, 6328, 8964, 8939], [1702, 5226, 7885, 2716]]


In [5]:
#word Enbedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 
import pandas as pd 

In [6]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6038 2979 8964 8556]
 [   0    0    0    0 6038 2979 8964  396]
 [   0    0    0    0 6038 7207 8964 6711]
 [   0    0    0 7852 1945 6301 2716 3246]
 [   0    0    0 7852 1945 6301 2716 4448]
 [   0    0    0  841 6038 6328 8964 8939]
 [   0    0    0    0 1702 5226 7885 2716]]


In [7]:
dim = 10 # feature representation
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')


c:\Users\yogit\OneDrive\Desktop\DeepLearning\RNN\SimpleRNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
#del model 

In [10]:
# Step 1: One-Hot Representation
vocab_size = 50  # Define vocabulary size (larger than the number of unique words)
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
print("One-Hot Representation:\n", one_hot_repr)

One-Hot Representation:
 [[17, 48, 42, 38], [17, 48, 42, 26], [17, 7, 42, 48], [9, 22, 27, 11, 15], [9, 22, 27, 11, 27], [47, 17, 16, 42, 8], [8, 8, 37, 11]]


In [11]:
# Step 2: Pad Sequences
sent_length = 8  # Fixed sentence length
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print("Padded Sequences:\n", embedded_docs)

Padded Sequences:
 [[ 0  0  0  0 17 48 42 38]
 [ 0  0  0  0 17 48 42 26]
 [ 0  0  0  0 17  7 42 48]
 [ 0  0  0  9 22 27 11 15]
 [ 0  0  0  9 22 27 11 27]
 [ 0  0  0 47 17 16 42  8]
 [ 0  0  0  0  8  8 37 11]]


In [12]:
# Step 3: Define the Embedding Layer
dim = 10  # Size of feature representation
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')


In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
# View the Embeddings
embeddings = model.predict(embedded_docs)
print("Embeddings Shape:", embeddings.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 733ms/step
Embeddings Shape: (7, 8, 10)


In [15]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Step 1: Prepare the sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

# Tokenize the sentences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sent)
sequences = tokenizer.texts_to_sequences(sent)
padded_sequences = pad_sequences(sequences, padding='post')
word_index = tokenizer.word_index

# Step 2: Load GloVe embeddings
embedding_index = {}
with open('glove.6B.50d.txt', 'r', encoding='utf-8') as file:
    for line in file:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype='float32')
        embedding_index[word] = vector

# Step 3: Create the embedding matrix
embedding_dim = 50  # GloVe uses 50, 100, 200, or 300 dimensions
vocab_size = len(word_index) + 1  # Add 1 for padding token
embedding_matrix = np.zeros((vocab_size, embedding_dim))

for word, i in word_index.items():
    embedding_vector = embedding_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

# Step 4: Define the model with pre-trained embeddings
model = Sequential()
embedding_layer = Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim,
    weights=[embedding_matrix],
    input_length=padded_sequences.shape[1],
    trainable=False  # Freeze embedding weights
)
model.add(embedding_layer)

model.compile('adam', 'mse')
model.summary()

# Step 5: Predict embeddings for the input sentences
embeddings = model.predict(padded_sequences)
print("Embeddings Shape:", embeddings.shape)


FileNotFoundError: [Errno 2] No such file or directory: 'glove.6B.50d.txt'